version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pyreon:
        patterns:
          - "@pyreon/*"
      tanstack:
        patterns:
          - "@tanstack/*"
      vitus-labs:
        patterns:
          - "@vitus-labs/*"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
